### ISSUE TITLE
Make arg checking (+syntax) more similar to directives

### ISSUE THREAD

**Issue by helfer** [apollostack/graphql-decorators#2]
Right now decorators use inputObjectType because with the tools provided in GraphQL-JS that's easier to process and validate. Many of the decorator validation functions are hardcoded into GraphQL-JS and not easily usable outside that context.

Here's what it looks like at the moment.

Directive: `@skip(if: true)`
Decorator: `+doc({ description: "The chosen one" })` (notice the extra `{}`)

It would be nice to make decorators and directives use the same code and have the same syntax.

**Comment by stubailo** [comment]
Is this resolved with the new addition to GraphQL-JS?

**Comment by helfer** [comment]
It is indeed!
